name: Package
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        node-version: [13.x]
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v1
    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}


    - name: yarn
      run: yarn
    - name: package
      run: yarn package
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyDcrn.exe
        path: ./release/MyDcrn-*.exe
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: MyDcrn.exe
