name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-lastest
    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn
      run: yarn
    - name: package
      run: yarn package
    - name: check i18n dupes
      run: yarn i18n-check-dupes
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyDcrn.exe
        path: ./release/MyDcrn-*.exe
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: MyDcrn.exe
