name: Package
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]
        python-version: ["3.6"]

    steps:
    - uses: actions/checkout@v1
    - name: Use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: yarn
      run: yarn
    - name: package
      run: yarn package
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyDcrn.dmg
        path: ./release/MyDcrn-*.dmg
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: MyDcrn.dmg
